function [ms_volumes, pt_age, pt_gender, pt_height, pt_weight, mss, lungs_vol] = mediastinum_main()
	addpath('C:\Users\Brian\Documents\School\4th Year\BME 4063\pulmonarytoolkit');
	addpath('C:\Users\Brian\Documents\School\4th Year\BME 4063\bresenham_line3d');
    addpath('C:\Users\Brian\Documents\School\4th Year\BME 4063\InsidePolyFolder');
    PTKAddPaths;
	source_paths = {'C:\Users\Brian\Downloads\1 output\1 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\1 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\2 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\3 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\6 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\7 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\8 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\9 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\10 output', ...
					'C:\Users\Brian\Downloads\12-11 new script\12-11 new script\11 output', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\12', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\13', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\14', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\15', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\16', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\17', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\18', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\19', ...
					'C:\Users\Brian\Downloads\12-16 new script\12-16 new script\21', ...
					'C:\Users\Brian\Downloads\3-17-19\26', ...
					'C:\Users\Brian\Downloads\3-17-19\27', ...
					'C:\Users\Brian\Downloads\3-17-19\28', ...
					'C:\Users\Brian\Downloads\3-17-19\29', ...
					'C:\Users\Brian\Downloads\3-17-19\30', ...
					'C:\Users\Brian\Downloads\3-17-19\31', ...
					'C:\Users\Brian\Downloads\3-17-19\32', ...
					'C:\Users\Brian\Downloads\3-17-19\33', ...
					'C:\Users\Brian\Downloads\3-17-19\34', ...
					'C:\Users\Brian\Downloads\3-17-19\35', ...
					'C:\Users\Brian\Downloads\3-17-19\36', ...
					'C:\Users\Brian\Downloads\3-17-19\37', ...
					'C:\Users\Brian\Downloads\3-17-19\38', ...
					'C:\Users\Brian\Downloads\3-17-19\39', ...
					'C:\Users\Brian\Downloads\3-17-19\40', ...
					'C:\Users\Brian\Downloads\3-17-19\41', ...
					'C:\Users\Brian\Downloads\3-17-19\42', ...
					'C:\Users\Brian\Downloads\3-17-19\43', ...
					'C:\Users\Brian\Downloads\3-17-19\44', ...
					'C:\Users\Brian\Downloads\3-17-19\45', ...
					'C:\Users\Brian\Downloads\3-17-19\46', ...
					'C:\Users\Brian\Downloads\3-17-19\47', ...
					'C:\Users\Brian\Downloads\3-17-19\48', ...
					'C:\Users\Brian\Downloads\3-17-19\49', ...
					'C:\Users\Brian\Downloads\3-17-19\50', ...
					'C:\Users\Brian\Downloads\3-17-19\51'};
	ptk_main = PTKMain();
	pt_age = cell(length(source_paths),1);
	pt_gender = cell(length(source_paths),1);
	pt_weight = zeros(length(source_paths),1);
	pt_height = zeros(length(source_paths),1);
	ms_volumes = zeros(length(source_paths),1);
    mss = cell(length(source_paths),1);
    lungs_vol = zeros(length(source_paths),1);
    voxel_sizes = cell(length(source_paths),1);
	for idx_dir = 1:length(source_paths)
		source_path = source_paths{idx_dir};
		disp(source_path);
		ds = ptk_main.Load(source_path);
		PTlungs = ds.GetResult('PTKLeftAndRightLungs');
		lungs = PTlungs.RawImage;
		ms = mediastinum4(lungs);
		VoxelSize = PTlungs.VoxelSize;
		
		vol_unit = VoxelSize(1) * VoxelSize(2) * VoxelSize(3);
		ms_unitless = sum(sum(sum(ms)));
		volume = ms_unitless * vol_unit;
		dicom_dir = dir(source_path);
		dicom_info = dicominfo([source_path '\' dicom_dir(3).name]);
		pt_age{idx_dir} = dicom_info.PatientAge;
		pt_gender{idx_dir} = dicom_info.PatientSex;
		pt_height(idx_dir) = dicom_info.PatientSize;
		pt_weight(idx_dir) = dicom_info.PatientWeight;
		ms_volumes(idx_dir) = volume;
        mss{idx_dir} = ms;
        voxel_sizes{idx_dir} = VoxelSize;

        lungs_unitless = sum(sum(sum(lungs)));
        lungs_vol(idx_dir)= lungs_unitless * vol_unit;
    end
    
  %   for idx_dir = 1:length(source_paths)
		% h = figure(1);
		% clf(h);
		% patch(isosurface(mss{idx_dir},.5),...
		% 'FaceColor',[.5,.5,.5],...
		% 'EdgeColor','none');
		% lighting gouraud
		% camlight
		% camlight
		% view(0,0);
		% pbaspect(VoxelSize)

		% z = input('What level is the diaphragm? ');
        
		% mss{idx_dir} = mss{idx_dir}(:,:,z:end);
  %       ms = mss{idx_dir};
        
  %       VoxelSize = voxel_sizes{idx_dir};
		% vol_unit = VoxelSize(1) * VoxelSize(2) * VoxelSize(3);
		% ms_unitless = sum(sum(sum(ms)));
		% volume = ms_unitless * vol_unit;
		% dicom_dir = dir(source_path);
		% dicom_info = dicominfo([source_path '\' dicom_dir(3).name]);
		% pt_age{idx_dir} = dicom_info.PatientAge;
		% pt_gender{idx_dir} = dicom_info.PatientSex;
		% pt_height(idx_dir) = dicom_info.PatientSize;
		% pt_weight(idx_dir) = dicom_info.PatientWeight;
		% ms_volumes(idx_dir) = volume;
  %   end
end